### PR TITLE
reword object store language

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by jmchilton** [comment]
I'm fine dropping the scratch storage language, but I really liked calling out TACC for credit. They are doing so much for us. Simplifying language is a good and valid concern but so is transparency. 🤷‍♀️

**Review by jmchilton — APPROVED** [review]
I am fine with change. I think the clarity on the second scratch storage is probably good.

I would change "is removed" to "is slated for removal" or maybe "is scheduled for removal" is we want to use simpler words but be a bit more vague. 

I would also add some disclosure around permanent not being actually permanent to cover our ass and to address Nate's valid concerns. I went and checked to see if have any language in https://usegalaxy.org/static/terms.html but we don't seem to.

**Comment by jmchilton** [comment]
Maybe we ping the brilliant legal mind of @blankenberg and see if he responds. I wouldn't wait on his response to move forward but I feel like there is some chance he'd be helpful and interested.

**Review by natefoo — APPROVED** [review]
Awesome, thanks @martenson

**Pull request merged**
