### PR TITLE
Give assignTaxonomyAddspecies more memory

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by gregvonkuster** [comment]
Thanks so much for this @davebx ;)

**Comment by natefoo** [comment]
The destination should be `dynamic_normal_16gb_reserved`. I don't recall why all the others are commented (maybe because I was testing resubmission?) but I'm pretty sure that's the destination you want.

**Comment by natefoo** [comment]
This is deployed.

**Comment by gregvonkuster** [comment]
Thanks so much @natefoo

**Comment by gregvonkuster** [comment]
@davebx @natefoo Testing resulted in the same memory error.  I have no idea how much ram this tool needs.  Can we bump it to the largest node?

**Comment by natefoo** [comment]
It looks like this tool is multicore, in which case it should use the `multi_tool` destination.

**Comment by gregvonkuster** [comment]
@natefoo @davebx I bumped into this attempting to push a change to increase the memory.
```
remote: Permission to galaxyproject/usegalaxy-playbook.git denied to gregvonkuster.
fatal: unable to access 'https://github.com/galaxyproject/usegalaxy-playbook.git/': The requested URL returned error: 403
```

**Pull request merged**
