### PR TITLE
Remove tools from the tool panel on main

### PR DESCRIPTION
**Pull request by davebx**
In keeping with galaxyproject/tools-iuc#1292

### CODE REVIEW

**Comment by martenson** [comment]
I think this has to be done on cvmfs, not in this repo @davebx

**Comment by natefoo** [comment]
True for the Galaxy-mutable ones (shed_, migrated_), but this is the correct place to modify tool_conf.xml.

**Comment by martenson** [comment]
we could have saved the whole https://github.com/galaxyproject/galaxy/issues/5302 if we followed through :/

Well at least we got an answer from biomart itself.

**Comment by martenson** [comment]
we could have saved the whole https://github.com/galaxyproject/galaxy/issues/5302 if we followed through :/

Well at least we got an answer from biomart itself.

I implemented the tool_conf changes in https://github.com/galaxyproject/usegalaxy-playbook/commit/9520aeab701220229f7b5c57a45b9364f91883b7

biomart and the other mart  have already been removed

**Pull request closed without merging**
